### ISSUE TITLE
If swap fails the BZZ values are not updated

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-desktop#194]
If the swap fails (and currently unfortunately this is quite often) then there is a state where the BZZ is already transferred, but the XDAI is still on the gift wallet address. In that case the values are not updated and it looks like that there is still BZZ on the gift wallet address **and** on the node wallet address at the same time.

<img width="1379" alt="Screenshot 2022-07-04 at 19 00 20" src="https://user-images.githubusercontent.com/230163/177196345-5584cc90-32ec-45ce-8137-ea1d9726e769.png">

**Comment by Cafe137** [comment]
May be improved by https://github.com/ethersphere/bee-dashboard/pull/465
