### ISSUE TITLE
Swarm Desktop not working on Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by TheBojda** [ethersphere/swarm-desktop#246]
I've installed Swarm Desktop from swarm-desktop_0.15.1_amd64.deb. 

When I start it, it stucks in the "Initializing..." phase.

Is there any log anywhere where I can find more info about the problem?

**Comment by agazso** [comment]
Yes, there are logs in `~/.local/share/Swarm Desktop` or `$XDG_DATA_HOME/Swarm Desktop`.

**Comment by TheBojda** [comment]
~/.local/share/Swarm Desktop exists, but empty

**Comment by TheBojda** [comment]
After some tries, it started, but could not connect to the bee client.

I tried to start bee by `~/.local/share/Swarm\ Desktop/bee start`, but it throws this error:

got error init chain: dial eth client: dial tcp 127.0.0.1:8546: connect: connection refused, shutting down... 
Error: init chain: dial eth client: dial tcp 127.0.0.1:8546: connect: connection refused

**Comment by agazso** [comment]
> After some tries, it started, but could not connect to the bee client.
> 
> I tried to start bee by `~/.local/share/Swarm\ Desktop/bee start`, but it throws this error:
> 
> got error init chain: dial eth client: dial tcp 127.0.0.1:8546: connect: connection refused, shutting down... Error: init chain: dial eth client: dial tcp 127.0.0.1:8546: connect: connection refused

If you start manually you need to specify the config file as well:
`~/.local/share/Swarm\ Desktop/bee start --config ~/.local/share/Swarm\ Desktop/config.yaml`

**Comment by TheBojda** [comment]
I started the node by `~/.local/share/Swarm\ Desktop/bee start --config ~/.local/share/Swarm\ Desktop/config.yaml` and now it's running, but no peer is connected.

There are some WARNs and ERRORs on the console:
...
WARN[2022-08-06T15:44:13+02:00] kademlia: discover to bootnode /dnsaddr/mainnet.ethswarm.org
...
ERRO[2022-08-06T15:44:17+02:00] cannot get chequebook balance
