### ISSUE TITLE
feat: show bee logs for debugging

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-desktop#256]
for 'advanced' users.

although i love  and applaud the idea of the guided node debugging, i think it will need to be developed and it would be good to provide  a view of what's going on.

a much easier option could be to include the location of the logs and perhaps even guidance on using `tail -f` or otherwise to view it somewhere in the app

**Comment by AuHau** [comment]
Agree it would be convenient to have it somewhere as part of UI, but if we are talking about advanced users, then they can have a look on this repo where we have it documented in README ;-)

**Comment by Cafe137** [comment]
@AuHau @agazso WDYT about adding a _Logs_ button to the tray options that opens the folder in the native file browser?

**Comment by AuHau** [comment]
Yeah, that sounds like good idea to me!
