### ISSUE TITLE
Failed to swap: Error: Request failed with status code 500

### ISSUE THREAD

**Issue by junyan-zg** [ethersphere/swarm-desktop#280]
![UPBJGQLD%7`PA93NM3A~LXO](https://user-images.githubusercontent.com/15311002/194726254-b10f1ae8-672e-4138-af1d-1ee69e1616e7.png)

**Comment by junyan-zg** [comment]
![image](https://user-images.githubusercontent.com/15311002/194726502-391bf217-344a-4369-81ee-9e25fcc2fd8d.png)

**Comment by agazso** [comment]
This may be because of a problem with the RPC endpoint. Retrying it later usually works. Did you manage to make it work?

**Comment by junyan-zg** [comment]
> This may be because of a problem with the RPC endpoint. Retrying it later usually works. Did you manage to make it work?

I only use the default setting, RPC endPoint : https://xdai.fairdatasociety.org. Am I wrong?

**Comment by nagydani** [comment]
> This may be because of a problem with the RPC endpoint. Retrying it later usually works. Did you manage to make it work?

I am getting the same error and changing to a different xDai RPC endpoint does not solve it.

**Comment by mjhd** [comment]
Any luck with this? Do we know if it’s a local issue or remote with the RPC or accessing the swap contract itself?

**Comment by 1337NFT** [comment]
having the same error, default endpoint, cant set wallet
