### ISSUE TITLE
Link od web site to macOS binary is wrong

### ISSUE THREAD

**Issue by tfius** [ethersphere/swarm-desktop#284]
Web site wrongly detects MacOS and gives a link to -arm image, when mac  is actually x86 based. 

<img width="430" alt="image" src="https://user-images.githubusercontent.com/1674145/195377668-44b79fd3-0979-4c72-9ca3-66011ce3de17.png">

Link on x86 macs should point to -x86 image

**Comment by Cafe137** [comment]
Thank you for reporting this issue!

We are tracking it in https://github.com/ethersphere/swarm-desktop/issues/282
