### ISSUE TITLE
Incorrect tray icon on Linux in dark mode

### ISSUE THREAD

**Issue by agazso** [ethersphere/swarm-desktop#291]
On Linux the tray icon is shown in the light version (black on transparent background) in dark mode therefore it's hardly visible:

![2022-10-28_16-59](https://user-images.githubusercontent.com/230163/198663856-2edff594-6533-40bc-bf7e-97f4180b8ba3.png)

**Comment by archerallstars** [comment]
This is still happening as of v0.53.1:

<img width="2136" height="1296" alt="Image" src="https://github.com/user-attachments/assets/346e3c43-f5b0-4ae2-bd23-0440a0d911f6" />
