### ISSUE TITLE
After installing swarm-desktop it downloads old bee node

### ISSUE THREAD

**Issue by IgorShadurin** [ethersphere/swarm-desktop#307]
After downloading swarm-desktop from https://www.ethswarm.org/build/desktop (https://github.com/ethersphere/swarm-desktop/releases/download/v0.16.0/Swarm.Desktop-0.16.0-x64.dmg) it installs old bee version and show that it is the latest version although 0.10.0 is available.
<img width="1212" alt="Screenshot 2022-12-20 at 14 18 30" src="https://user-images.githubusercontent.com/1595061/208654907-89775977-e36c-41e9-8978-0b6dec1e7d95.png">

**Comment by agazso** [comment]
There is a new version available that is compatible with Bee 1.10.0:
https://github.com/ethersphere/swarm-desktop/releases/tag/v0.17.0
