### ISSUE TITLE
feat: show capacity rather than depth

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-desktop#337]
choose with a slider by capacity/ttl rather than depth and having to enter in different values for ttl

<img width="1262" alt="Screenshot 2023-04-24 at 11 26 48" src="https://user-images.githubusercontent.com/130104/233970587-2207890c-2d16-4547-ac98-344ed0ea6094.png">

**Comment by Cafe137** [comment]
Tracked in https://github.com/ethersphere/swarm-desktop/issues/109
