### ISSUE TITLE
feat: add current log file to "settings" page for debugging

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-desktop#344]
add to the "desktop settings" list after Data DIR

<img width="1224" alt="Screenshot 2023-05-04 at 08 08 05" src="https://user-images.githubusercontent.com/130104/236134325-c71d09f3-1003-4e06-9a89-58d6c7f9cbfc.png">

**Comment by Cafe137** [comment]
The `Logs` item in the tray is sufficient
