### ISSUE TITLE
fix: fix padding in Account -> Chequebook

### ISSUE THREAD

**Issue by significance** [ethersphere/swarm-desktop#348]
the padding above the buttons should be the same as in the rest of the app

correct 
<img width="934" alt="Screenshot 2023-05-04 at 08 18 01" src="https://user-images.githubusercontent.com/130104/236136401-d158e21f-dc06-4d51-8cf3-356d1f690fb3.png">

incorrect (needs fixing)
<img width="1358" alt="Screenshot 2023-05-04 at 08 17 33" src="https://user-images.githubusercontent.com/130104/236136406-841cbc89-30a6-47c5-876d-56fa5d589ec4.png">

**Comment by ferencsarai** [comment]
PR: https://github.com/ethersphere/bee-dashboard/pull/635
