### ISSUE TITLE
freez at stamp listing

### ISSUE THREAD

**Issue by tamas6** [ethersphere/swarm-desktop#409]
<img width="1074" alt="Screenshot 2024-01-17 at 12 24 14" src="https://github.com/ethersphere/swarm-desktop/assets/81620050/5b9bad31-28b6-4eae-bdab-89add340e915">

this was a dead spinning loop, was able to navigate betweeen pages, checking functions, but the Stamp section remained in this state.
Occured at launch, this v0.36.0 was used several times but never behaved like this.
Counter measure was to relaunch chrome 🧐 and the bug was solved. ✅

I hope this report is useful.

**Comment by Cafe137** [comment]
Fixed in https://github.com/ethersphere/bee-dashboard/pull/670
